#!/usr/bin/env bash
# prints domain and subdomain info

dig_all () {
	dig "$1" | grep -A1 'ANSWER SECTION' | awk '
	/ANSWER SECTION:/ {next}
	{print "The subdomain " substr($1, 1, index($1, ".") - 1) " is a " $4 " record and points to " $5}
	'
}

if [ "$2" ]
then
	domain="$1"
	dig_all "$2.$domain"
	exit 0
fi

dig_all "www.$1"
dig_all "lb-01.$1"
dig_all "web-01.$1"
dig_all "web-02.$1"
