#!/usr/bin/env bash
# setups nginx on my webserver
apt-get update
apt-get install nginx -y

echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
