#!/usr/bin/env bash
# setups nginx on my webserver
apt-get update
apt-get install nginx -y
sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        try_files /index.html =404;
    }

    location /redirect_me {
    	return 301 https://www.youtube.com/watch?v=6KFOcDmcoBg ;
   }
}" > /etc/nginx/sites-available/default

nginx -s reload
