#!/usr/bin/env bash
# setups nginx on my webserver
apt-get update
apt-get install nginx -y
sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "server {
    listen 80;

    location / {
        root /var/www/html;
    }

    location /redirect_me {
    	return 301 https://www.youtube.com/watch?v=6KFOcDmcoBg;
	}
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
	internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
