#!/usr/bin/env bash
# Configures HAProxy
apt-get update
apt-get install haproxy -y
echo "
frontend thore.tech
	bind *:80
	default_backend web_servers

backend web_servers
	mode http
	balance roundrobin
	server 339486-web-01 100.26.229.162:80 check
	server 339486-web-02 54.174.85.129:80 check 
" > /etc/haproxy/haproxy.cfg
service haproxy restart
