#!/usr/bin/env bash
# Configures HAProxy
apt-get update
apt-get install haproxy -y
echo "
frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server 339486-web-01 54.82.134.179:80 check
	server 339486-web-02 34.224.16.69:80 check 
" > /etc/haproxy/haproxy.cfg
systemctl restart haproxy
systemctl enable haproxy
