#!/usr/bin/env bash
# Creates a mysql dumb of all databases and zips the file into an archive 
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$(date +'%d-%m-%Y')".tar.gz ./backup.sql

