#!/usr/bin/env bash
# installs nginx and configures in correctly
apt-get update
aptget install nginx -y
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
echo "
events {}
http {
	server {
		listen *:80;
	}
}" > /etc/nginx/nginx.conf
service nginx restart

