#!/usr/bin/env bash
# changes nginx server config to listen on port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
