#!/usr/bin/env bash
# run  nginx as nginx
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bk
echo "
user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080 default_server;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }
}" /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /usr/share/nginx/html
sudo chown -R nginx:nginx /var/log/nginx
sudo chmod -R 755 /usr/share/nginx/html
sudo chmod -R 755 /var/log/nginx
su -s /bin/bash -c 'sudo service nginx restart' nginx  
